[tool.poetry]
name = "airguardian"
version = "0.1.0"
description = "A FastAPI application for air quality monitoring"
authors = [
    "fdessoy- <fdessoy-@hive.student.fi>",
    "zfarah <zfarah@hive.student.fi>"
]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.116.1"
psycopg = {extras = ["binary"], version = "^3.2.9"}
uvicorn = {extras = ["standard"], version = "^0.35.0"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
black = "^23.0.0"
mypy = "^1.0.0"

[tool.poetry.scripts]
dev = "uvicorn airguardian.src.main:app --reload"
start = "uvicorn airguardian.src.main:app"
test = "pytest"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"